version: "3.7"

services:

    # ===== Primary Services =====
    # PHP Service
    php:
        container_name: ${PROJECT_NAME}_php
        build:
            args:
                user: laravel
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: ${PROJECT_NAME}_php
        restart: always
        working_dir: /var/www/
        volumes:
            - ./:/var/www
            - ./.docker/php/local.ini:/etc/php.d/local.ini
        networks:
            - app-network

    # Nginx Service
    nginx:
        container_name: ${PROJECT_NAME}_nginx
        image: nginx:1.21.6-alpine
        restart: always
        ports:
            - ${NGINX_HTTP_PORT}:80
        volumes:
            - ./:/var/www
            - ./.docker/nginx/:/etc/nginx/conf.d/
        depends_on:
            - php
            - mysql
            - redis
        networks:
            - app-network

    # MySQL Service
    mysql:
        container_name: ${PROJECT_NAME}_mysql
        image: mysql:8
        restart: always
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD_ROOT}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
        volumes:
            - mysql-data:/var/lib/mysql
        ports:
            - ${MYSQL_PORT}:3306
        networks:
            - app-network

    # Redis Service
    redis:
        container_name: ${PROJECT_NAME}_redis
        image: redis:7.0.2-alpine
        restart: always
        volumes:
            - redis-data:/data
        networks:
            - app-network

    # Mailhog Service
    mailhog:
        container_name: ${PROJECT_NAME}_mailhog
        image: mailhog/mailhog:v1.0.1
        restart: always
        ports:
            - ${MAILHOG_PORT}:1025
            - ${MAILHOG_PORT_WEB}:8025
        networks:
            - app-network

    # ===== On-demand Services =====
    # Node Service
    npm:
        container_name: ${PROJECT_NAME}_npm
        image: node:16-alpine
        working_dir: /var/www/
        entrypoint: ['npm']
        user: node
        environment:
            NPM_CONFIG_LOGLEVEL: warn
        volumes:
            - ./:/var/www
            - ./.npmrc:/var/www/.npmrc
        networks:
            - app-network

    # Composer Service
    composer:
        container_name: ${PROJECT_NAME}_composer
        image: ${PROJECT_NAME}_php
        working_dir: /var/www/
        entrypoint: ['composer']
        volumes:
            - ./:/var/www
        networks:
            - app-network

    # Artisan Service
    artisan:
        container_name: ${PROJECT_NAME}_artisan
        image: ${PROJECT_NAME}_php
        working_dir: /var/www/
        entrypoint: ['php', 'artisan']
        volumes:
            - ./:/var/www
        depends_on:
            - mysql
        networks:
            - app-network

    # ===== Worker Services =====
    # Npm Watch Service
    npm_watch:
        container_name: ${PROJECT_NAME}_npm-watch
        image: node:16-alpine
        restart: unless-stopped
        working_dir: /var/www/
        entrypoint: ['npm', 'run', 'watch']
        user: node
        environment:
            NPM_CONFIG_LOGLEVEL: warn
        volumes:
            - ./:/var/www
            - ./.npmrc:/var/www/.npmrc
        networks:
            - app-network

    # Queue Service
    queue:
        container_name: ${PROJECT_NAME}_queue
        image: ${PROJECT_NAME}_php
        restart: unless-stopped
        working_dir: /var/www/
        entrypoint: ['php', 'artisan', 'queue:work']
        volumes:
            - ./:/var/www
        depends_on:
            - redis
        networks:
            - app-network

    # Schedule Service
    schedule:
        container_name: ${PROJECT_NAME}_schedule
        image: ${PROJECT_NAME}_php
        restart: unless-stopped
        working_dir: /var/www/
        entrypoint: ['php', 'artisan', 'schedule:work']
        volumes:
            - ./:/var/www
        depends_on:
            - mysql
        networks:
            - app-network

networks:
    app-network:
        driver: bridge

volumes:
    mysql-data:
        driver: local
    redis-data:
        driver: local
